# File Path: ~/.bash_aliases or ~/.alias

alias aptupdate='sudo apt update && sudo apt upgrade && sudo apt autoremove && sudo apt autoclean && sudo apt clean'
alias aria='aria2c'
alias arp='ip neigh'
alias cat='cat -v'
alias cdrandom='cd ~/Documents/random/'
alias entropyleft='cat /proc/sys/kernel/random/entropy_avail'
alias fw4list='sudo iptables -nvL --line-numbers'
alias fw4load='sudo iptables-restore < /etc/iptables/rules.v4'
alias fw4save='sudo iptables-save > /etc/iptables/rules.v4'
alias fw6list='sudo ip6tables -nvL --line-numbers'
alias fw6load='sudo ip6tables-restore < /etc/iptables/rules.v6'
alias fw6save='sudo ip6tables-save > /etc/iptables/rules.v6'
alias ifconfig='ip a'
alias last='sudo last -aw'
alias lastb='sudo lastb -aw'
alias ll='ls -alF'
alias mtr='mtr -no "LSD NBAW VJ"'
alias netstat='ss -n -tudwSM'
alias nst='ss -nptu'
alias nstl='ss -lnptu'
alias nsts='ss -nptu | tail -n +2 | sort -k 6V'
alias orphaned='sudo zypper packages --orphaned'
alias pbcopy='xsel --input --clipboard'
alias pbpaste='xsel --output --clipboard'
alias ping='ping -Q 192 -n'
alias ping6='ping6 -Q 192 -n'
alias price-btc='echo -n "BTCUSD: " ; curl -sS "https://api.coinbase.com/v2/prices/BTC-USD/spot" | jq -r ".data.amount"'
alias price-doge='echo -n "DOGEUSD: " ; curl -sS "https://api.coinbase.com/v2/prices/DOGE-USD/spot" | jq -r ".data.amount"'
alias price-eth='echo -n "ETHUSD: " ; curl -sS "https://api.coinbase.com/v2/prices/ETH-USD/spot" | jq -r ".data.amount"'
alias price-usdt='echo -n "USDTUSD: " ; curl -sS "https://api.coinbase.com/v2/prices/USDT-USD/spot" | jq -r ".data.amount"'
alias price-xmr='echo -n "XMRUSD: " ; curl -sS "https://api.coinbase.com/v2/prices/XMR-USD/spot" | jq -r ".data.amount"'
alias route='ip r'
alias showdns='cat /etc/resolv.conf | grep "^nameserver"'
alias speedtest='speedtest --progress-update-interval=100 --precision=3 --selection-details'
alias sshdt='sudo sshd -t'
alias sshdr='sudo service ssh restart'
alias tfoflush='sudo ip tcp_metrics flush'
alias tfolist='ip tcp_metrics show | grep "fo_cookie"'
alias tfostat='grep "^TcpExt:" /proc/net/netstat | cut -d " " -f 85-91 | column -t'
alias tracert='sudo traceroute -I -N 3 -t 192 -w 1 -z 0.1'
alias tracertu='sudo traceroute -N 3 -t 192 -w 1 -z 0.1'
alias trim='sudo fstrim -av'
alias unneeded='sudo zypper packages --unneeded'
alias update='sudo echo "===== Updating zypper =====" ; sudo zypper refresh && sudo zypper dist-upgrade ; sudo zypper clean ; sudo zypper cleanlocks ; echo "===== Updating flatpak =====" ; sudo flatpak update ; sudo flatpak uninstall --unused ; echo "===== Updating yt-dlp =====" ; yt-dl -U'
alias updateforce='sudo echo "===== Updating zypper =====" ; sudo zypper refresh --force'
alias whois='whois -H'
alias wifilist='nmcli -f "IN-USE,SSID,BSSID,MODE,CHAN,RATE,SIGNAL,SECURITY,RSN-FLAGS" device wifi list'
alias wifirescan='nmcli device wifi rescan'
alias xxd='xxd -c 32'
